spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lowerCaseServiceId: true

server:
  port: 8765
  address: 127.0.0.1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

#management:
#  endpoints:
#    web:
#      exposure:
#        include: *

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG

#management:
#  tracing:
#    sampling:
#      probability: 1.0
#  zipkin:
#    enabled: true
#    endpoint: "http://localhost:9411/api/v2/spans"
#
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Product Service
        url: /products/v3/api-docs
      - name: Auth Service
        url: /auth/v3/api-docs
  default-group-name: Gateway
